export default {
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  USER_CHANGE_NAME: 'USER_CHANGE_NAME',

  MESSAGE_ADD: 'MESSAGE_ADD',

  SET_CONNECTION: 'SET_CONNECTION',

  GET_INFO: 'GET_INFO',

  INFO_UPDATED: 'INFO_UPDATED',
}
